language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:travis || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - REPO_NAME=carded-table
  - OWNER_NAME=BrightspaceUILabs
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: bUjh/iA+C4E7rEVb48XtXLFdSlkVS61SRtXdEZqC8vYZBdaNCJ9PSRNPgwQiQFCoXkS1DpkBAWqhZ72GV67ZRlpX+Ik7WSx1RRkIrsw3ZpuyAYx7zWPOuymGtFSScI7nTZfduy6JFzgxkgRhTAkwI54j+Oae+Hh0m1auL37xSjG5J+d4u+C+dtpRluU2JqKTRvwGJ0MNNCyYZrEjvgwbpsariTRAvnqRYUBd02dK8VdqcPuiG02ABe+tbrrxu2bi+Awqv8C86f26GnGd9NCJ1lHfmcHOZEkxJK8hXPZIcQaWPY0oiQ5tlzz4LyyULh0pTEr9RzB3djzBM9EN5zKDdwN4EU7TNJ6gMLjjMytu76aZQ7Xu4zu6/eTp/7qg/jamdL6dy2Owc/QGvWuo1gRc4k7eUAY0mT2sZpPxjs2lXuW3WZiajYicnKEjfTS/mLNpnZn7ijl0hsn7pvXED/R3tT8GGR6mylsdr0M1Tvq9J1kD7sKM6vdV+VBxyySeJRqtUBYftkkauBopavmEW67QaIdX4ILPWligzA2AEoGUfJtq8RO1a9+ZwV6QzmRBzHg/8T0RxEV7t+65z7RfKqkrduvfRNmS2SszjUErYgmqosasb5P2l2xVxmf6QUhATwfDFX4zDB72n5H17onRqo9ZDkKU32wDNCgT1jJaunEQ4M0=
  # GITHUB_RELEASE_TOKEN (2d5a......c3a6)
  - secure: ovAOhFaiOqgntxx2L7pde+rK0yzPFZdNVExm4+PGqIMSJOWMAYgvcqlLvLxH5yWnm4ZGz2OPakua0D/islff5jK3bBbNCozzVwePFdxQgSqY2Bvg5Vx3e1GEX2+s2TEidOqKudMbddsLBWxpGu0coGihcg/BrSG2O/PaOMOXUudhJI9iyIiMxOXZRd66H4Sp23cDF5iSGO3SR88w6n0NL0FnbW+OOZMuP6R8+MIHeIElegOkJ59i63NtvuPLpebbbgzwR7Bfo0GP5MYnhvhobnnagydqzeB1tDK5KJ1ImuRRADrDK27VuHolK4OlSUSXydf0z9cgJgYDS7n8cuCnyVmiYho+0Ys2Hj+/2SjppYeHh/EDy6afB9IjST7rTTrxvrQfWyALo9UBlRJRFA01zKgHfpEWluAKlVrIwRIZkdbaaqxdPGzRpopZK0I7gslxCs9y9tlvZNel6M2Yo9GeJQdyU9BKA1DtZvBsTe7m2nYLhQgZ0sVM0EbvoulbuJSbMJsOiNrBFkGORm8LMEoS0DOL19xk19Oa4YXVtlJeUT/voZshgOECWTq3LpaSg4XsdGbNitseCZnam1dZSCAWWYMA2lJpk1gtSnqX3NwUfAL0PyZepFtYY8jyN8BLREcB/rFJCPS+LbS5vQDyQVST0yP242gWOuOkzvOT2pjOh3o=
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
    # 1f6d......937b
    secure: IxPlGflcAyLB84CAdE+6ojTE2199yFMMn8LAG2Hay/lPJXsCdbRqJ77NK7Yju2wENJ/IqI/JgQeWGvAM8JrSg8WSb05wkr4kdUMiXsFqw2nzMOC02reYH+4kRMV9zT+2Yd11SVZda7Q5ctyDVMppqNCIRh3gd8RKiRjWz1efyxVlk2fx3k63jXECLggnNHs6ULmBG57b3Oeul6PO+gr4yPNnCN+GB8SOMeJh3+so5ITAuZ8HWsdZWZaE7tiJy3pM6lbdnRSN58BA3kl/g3KoFRZu+1oVKbembSweUk2KgA5Nw0lDiPTrdmmTbL6zUOyLQh85yCFnRFmrkCW6jQf0C87QWjn+HU5jdOQkveDBoy31qyBKrLu2m7YiXdGIvhpk4DYtM4mJ+qaVNTG/uZQaMrO4soPH4Zg3epOrfQeeuS7EPiKPU3mbE2YKS1iyZrudkYnieBcMs70RoeyywtWaOx0NmuDDKF+sSFetsGSJ+tHIOPcy0TYSdZNbmRfOPfHEkzZvWAWHOQ3Lqn37NRPN++IgcI1hhpdVOWKavWP2DYeDvrR4HP85lNLySKC1NM6DIoEp+4ABsEB/Rs/Tz7sJcTLQcVPa7INTK37SQk3y7mAWbB5X9MB7r0ZE7ZoftNNiDdWYlHdh15/extEAUb2zFe+L/16mZakJbldT1761qfI=
  on:
    tags: true
    repo: BrightspaceUILabs/carded-table
